#!/usr/bin/env python3

# This file is part of pbd.
#
# Copyright (c) 2011 Dustan Bower.
#
# pbd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# pbd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pbd.  If not, see <http://www.gnu.org/licenses/>.

from contextlib import suppress
from enum import StrEnum
import os
import re
import subprocess
import sys
from time import sleep

import pb


class InputStatus(StrEnum):
    """
    The status of parsing for user input, used for flow-control.

    """
    OK = "ok"
    NEW_PROMPT = "new_prompt"
    UNIMPLEMENTED = "unimplemented"


def check_running():
    """
    Check to see if we're already running.

    :return: None

    """

    try:
        _ = subprocess.check_output("pgrep pianobar", shell=True)
    except subprocess.CalledProcessError:
        startup()
        return False

    return True


def startup():
    """
    Start up pianobar and listen for events.

    :return: None

    """

    process = subprocess.Popen(['pianobar'],
                               stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE)

    # if necessary, create the tempfile we use to receive information from
    # pianobar
    f = open("/tmp/pbd.tmp", 'w', encoding="utf-8")
    f.close()
    pb.display("Starting up...")
    while True:
        if process.stdout is None:
            raise AttributeError("process.stdout is None")
        output = process.stdout.readline().decode("utf-8")
        if not output:
            # if pianobar is closed, break
            if process.returncode is None:
                break

            sleep(1)  # wait a second for new output
            continue
        process_pianobar_output(output)


def process_pianobar_output(output):
    """
    Process pianobar output and relay it if necessary.  If we have an error,
    we need to notify the user of it.

    :param output: pianobar output
    :return: None

    """

    display = ["We're playing this track because", "Network error:", "Error:"]
    for message in display:
        substring = output.find(message)
        if substring != -1:
            pb.display(output[substring:])


def load_data():
    """
    read data from pianobar

    :return: None
    """

    with open("/tmp/pbd.tmp", "r", encoding="utf-8") as f:
        user_input = f.read()

    return pb.datadict(user_input)


def prompt_station():
    """
    prompt user for station

    :return: None
    """

    stations = []
    highest = 0
    regex = re.compile(r"station[0-9]")
    data = load_data()
    for key in data.keys():
        if regex.match(key):
            stations.append(key)
            # slice after the 'station' in the input: 'station11' -> '11'
            if int(key[7::]) > highest:
                highest = int(key[7::])

    known_inputs = []
    for station in range(0, highest + 1):
        station_key: str = f"station{station}"
        known_inputs.append(f"{station}) {data[station_key]}")

    user_input = pb.prompt(known_inputs, display_prompt="(station) ")
    return user_input


def show_no_dash_args():
    """
    Called from the command line with -h or --help.

    :return: None

    """
    # FIXME: make pb.display() take an end= parameter to allow multiple
    # FIXME: strings to be sent and concatenated until the normal end=
    # FIXME: is received.
    string = """To avoid confusion with - and accidentally disliking songs, \
pbd does not support options beginning with \"-\".  Options \
are prefixed with : instead.
Showing 'pbd :help'."""
    pb.display(string, timeout=10000)
    show_help()


def show_help():
    """
    display help message

    :return: None

    """

    string = ""
    option = False
    for command, description in pb.INPUTS:
        # give the :help input special formatting
        separator = ": " if command[0] != ":" else "     "

        new_line: str = f"{command}{separator}{description}\n"

        # Separate options by linefeed.
        if new_line[0] == ":":
            if not option:
                option = True
                string += "\n"
        string += new_line

    pb.display(string, timeout=10000)


# Fetching the initial character this way over and over is
# less efficient, but it is cleaner code than passing user_input
# and initial_character around all the time. It's also simple
# enough that it's unlikely to ever affect performance.
def get_initial_character(user_input: str) -> str:
    """
    Grab the initial character. If there isn't one,
    turn this into a help command instead by adding
    `?`

    """
    try:
        return user_input[0]
    except IndexError:
        return "?"


def handle_basic_commands(user_input: str) -> bool:
    """
    Handle basic commands. If a basic command was found and processed,
    return true.
    """
    handled: bool = False
    initial_character: str = get_initial_character(user_input)
    # pass basic commands directly to pianobar
    if initial_character not in [':', '?']:
        if user_input == "q":
            # display song lyrics on quit for no good reason
            pb.display("Shutting down...")
        os.system(f"echo -n '{user_input}' > ~/.config/pianobar/ctl")
        handled = True

    return handled


def handle_pbd_commands(user_input: str) -> bool:
    """
    Handle pbd-specific commands. If a command is handled this way,
    return True.

    """
    handled: bool = False
    initial_character: str = get_initial_character(user_input)
    if initial_character == ":":
        # parse args
        if user_input == ":help":
            show_help()
        if user_input == ":station":
            station_number = None
            station = prompt_station()
            try:
                station_number = station.split(")", 1)[0]
            except AttributeError:
                pass
            station_string = "s" + str(station_number)
            os.system(f"echo '{station_string}' > ~/.config/pianobar/ctl")
            handled = True

    return handled


def handle_default_commands(user_input: str) -> bool:
    """
    Handle commands not considered basic commands or pbd-specific.

    """
    handled: bool = False
    data = load_data()
    initial_character: str = get_initial_character(user_input)
    try:
        argument = user_input[1::]
    except IndexError:
        argument = None

    # display song info by default
    if not argument or initial_character == "?":
        pb.display(pb.get_song_title_display(data),
                   heading=pb.get_station_display(data))
        handled = True

    return handled


def handle_input() -> dict[str, str]:
    """
    Handle input from user. Old way of parsing user input was a mess
    and resulted in too high of a cyclomatic complexity, so some
    of it has been refactored here.

    """
    user_input: str = ""
    status: str = InputStatus.OK

    with suppress(IndexError):
        user_input: str = sys.argv[1].strip()

    if not user_input:
        known_inputs: list[str] = [(x[0] + " ").strip() for x in pb.INPUTS]
        user_input = pb.prompt(known_inputs, delay=0)

    # Called with no input, prompt for input
    if user_input and user_input[0] == '-' and user_input not in ["-", "--"]:
        show_no_dash_args()
        status = InputStatus.NEW_PROMPT

    if user_input in pb.UNIMPLEMENTED_COMMANDS:
        status = InputStatus.UNIMPLEMENTED

    # prompt for station if no station specified, otherwise switch to
    # selected station
    if user_input == "s":
        user_input = ":station"
    elif user_input[0] == "s":
        regex = re.compile(r"s[0-9]")
        if regex.match(user_input):
            handled_input: str = user_input + '\n'
            os.system(f"echo '{handled_input}' > ~/.config/pianobar/ctl")
        status = InputStatus.NEW_PROMPT

    return {
        'user_input': user_input,
        'status': status,
    }


def pbd():
    """
    main function, called each time pbd is invoke via hotkey/etc.

    :return: None

    """

    if not check_running():
        return

    parsed_input = handle_input()
    status: str = parsed_input['status']

    if status not in [InputStatus.OK]:
        return

    user_input: str = parsed_input['user_input']

    if handle_basic_commands(user_input):
        pass
    elif handle_pbd_commands(user_input):
        pass
    else:
        handle_default_commands(user_input)


if __name__ == "__main__":
    pbd()
