#!/usr/bin/env python3

# This file is part of pbd.
#
# Copyright (c) 2011 Dustan Bower.
#
# pbd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# pbd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pbd.  If not, see <http://www.gnu.org/licenses/>.

"""Event script called by pianobar"""

import logging
import os
import sys

from platformdirs import PlatformDirs
import yaml

import pb


DEBUG = False

dirs = PlatformDirs("pbd", "pbd", ensure_exists=True)
# load config
dirs.user_config_path
config_path = os.path.join(dirs.user_config_path, 'config.yml')
with open(config_path, 'r', encoding="utf-8") as file:
    config_file = yaml.safe_load(file)

    DEBUG = config_file.get("debug")

# SET UP LOGGING
logger = logging.getLogger(__name__)
log_path = os.path.join(dirs.user_log_dir, 'pbevent.log')
logging.basicConfig(filename=log_path, encoding='utf-8', level=logging.DEBUG)


# load pianobar input and write it to /tmp/pbd.tmp
pianobar_input = f"event={sys.argv[1]}\n"
pianobar_input += "".join(sys.stdin.readlines())
dirs = PlatformDirs("pbd", "pbd", ensure_exists=True)
data = pb.datadict(pianobar_input)
with open("/tmp/pbd.tmp", 'w', encoding="utf-8") as f:
    f.write(pianobar_input)

if DEBUG:
    logger.debug("pianobar_input: %s\n", pianobar_input)
    logger.debug("data: %s\n", data)

song_title = pb.get_song_title_display(data)
station = pb.get_station_display(data)

# special handling for certain events
if data['event'] == "songstart":
    if DEBUG:
        logger.debug("songstart: %s, station=%s\n", song_title, station)
    pb.display(song_title, heading=station)

if data['event'] == "songban":
    if DEBUG:
        logger.debug("songban: %s, station=%s", song_title, station)
    pb.display(f"Banning song: [{song_title}]", heading=station)

if data['event'] == "songlove":
    if DEBUG:
        logger.debug("songlove: %s, station=%s", song_title, station)
    pb.display(f"Loving song: [{song_title}]", heading=station)

if data['event'] == "songshelf":
    if DEBUG:
        logger.debug("songshelf: %s, station=%s", song_title, station)
    pb.display(f"Shelving song: [{song_title}]", heading=station)
