#!/usr/bin/env python2

## This file is part of pbd.
##
## Copyright (c) 2011 Dustan Bower.
##
## pbd is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 2 of the License, or
## (at your option) any later version.
##
## pbd is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with pbd.  If not, see <http://www.gnu.org/licenses/>.

from copy import copy
import os
import sys

debug = True

input = "event=%s\n" % sys.argv[1]
input += "".join(sys.stdin.readlines())
data = dict([x.split('=', 1) for x in input.split('\n') if x])
file = open("/tmp/pbd.tmp", 'w')
file.write(input)
file.close()

if debug:
    print(data)
    print("'%s'" % (data['event']))

if data['event'] in ["songstart", "songexplain"]:
    os.system("notify-send -t 5000 \"pbd: [%s]\" \"%s - %s\"" % (data['stationName'], data['artist'], data['title']))

if data['event'] == "songban":
    os.system("notify-send -t 5000 \"pbd: [%s]\" \"Banning song: [%s - %s]\""
              % (data['stationName'], data['artist'], data['title']))

if data['event'] == "songlove":
    os.system("notify-send -t 5000 \"pbd: [%s]\" \"Loving song: [%s - %s]\""
              % (data['stationName'], data['artist'], data['title']))

if data['event'] == "songshelf":
    os.system("notify-send -t 5000 \"pbd: [%s]\" \"Shelving song: [%s - %s]\""
              % (data['stationName'], data['artist'], data['title']))

